name: Release Docker Image

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

env:
  # Set this repository variable in GitHub: Settings -> Secrets and variables -> Actions -> Variables
  # Example value: your-dockerhub-username/mp3tagger
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}

jobs:
  docker-release:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate tag format (X.Y.Z)
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ERROR: Invalid tag '$TAG'. Tags must follow the format X.Y.Z (e.g., 1.2.3)." >&2
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: env.DOCKERHUB_REPO != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Validate DOCKERHUB_REPO is configured
        run: |
          if [ -z "${{ env.DOCKERHUB_REPO }}" ]; then
            echo "ERROR: Repository variable DOCKERHUB_REPO is not set. Configure it in GitHub -> Settings -> Secrets and variables -> Actions -> Variables." >&2
            exit 1
          fi

      - name: Extract version from tag
        id: vars
        run: |
          echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Mp3Tagger.Web/Dockerfile
          push: true
          # Build for common platforms; adjust if you only want linux/amd64
          platforms: linux/amd64
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ steps.vars.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ steps.vars.outputs.version }}

    # Notes:
    # - Set repository secrets DOCKERHUB_USERNAME and DOCKERHUB_TOKEN (a Docker Hub access token).
    # - Set repository variable DOCKERHUB_REPO to your Docker Hub repo name (e.g., myuser/mp3tagger).
    # - The image tag exactly matches the Git tag name (e.g., 1.2.3).
